<?php

namespace Views;

use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Config\Services;
use Models\CategoryLocalModel;
use Models\CategoryModel;
use Models\CustomFileModel;
use Models\SettingModel;
use Psr\Log\LoggerInterface;

class BaseClientController extends BaseViewController
{
    protected CategoryModel $categoryModel;
    protected CategoryLocalModel $categoryLocalModel;
    protected SettingModel $settingModel;
    protected CustomFileModel $customFileModel;
    /**
     * links for pages
     * @var string[]
     */
    protected array $links = [];

    /**
     * to check login when user access page automatically
     * @var bool
     */
    protected bool $isCheckLogin = false;

    public function __construct()
    {
        $this->categoryModel = model('Models\CategoryModel');
        $this->categoryLocalModel = model('Models\CategoryLocalModel');
        $this->settingModel = model('Models\SettingModel');
        $this->customFileModel = model('Models\CustomFileModel');

        // must be same with [\API\CategoryController - getCategoryAll()]
        $categories = $this->categoryModel->get();
        foreach ($categories as $i => $category) {
            if ($category['has_local'] == 1) {
                $paths = $this->categoryLocalModel->get([
                    'category_id' => $category['id'],
                ]);
                $categories[$i]['locals'] = $paths;
            }
        }
        $this->links = $categories;
    }

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        $this->setLanguage();
        if ($this->isCheckLogin) {
            $this->checkLogin();
        }
    }

    /**
     * login 상태일 때 페이지에 대한 접근 체크 기능
     * @return void
     */
    protected function checkLogin(): void
    {
        if ($this->session->is_login) {
            $response = Services::response();
            $response->setBody(view('/redirect', [
                'path' => '/profile',
            ]));
            $response->sendBody();
            exit;
        }
    }

    /**
     * 공통 header 부분 출력 기능
     * @param array $data
     * @param array $initData
     * @return string
     */
    protected function loadHeader(array $data, array $initData = []): string
    {
        $logos = $this->customFileModel->getLogos();
        $initData = array_merge($initData, [
            'links' => $this->links,
            'logos' => $logos,
        ]);
        return view('client/header', parent::loadDataForHeader($data, $initData));
    }

    /**
     * 공통 footer 부분 출력 기능
     * @return string
     */
    protected function loadFooter(): string
    {
        return view('client/footer');
    }

    /**
     * body 출력 시에 공통적으로 load 될 데이터 호출 기능
     * @return array
     */
    protected function getViewData(): array
    {
        $settings = [];
        $settingResult = $this->settingModel->get();
        foreach ($settingResult as $item) {
            $settings[$item['code']] = $item['value'];
        }

        return array_merge(parent::getViewData(), [
            // todo translation
            'company_info' => [
                'name' => '(주)유닉코퍼레이션',
                'ceo_name' => '손윤정',
                'cs_center' => '010-5692-2500 (평일 10:00 ~ 19:00)',
                'company_number' => '555-81-02851',
                'certification_number' => '제2024-서울서초-0338호',
                'address' => '서울 서초구 사임당로8길 13, 4층 402호 N91호',
                'email' => 'contact@unyk.kr',
                'manager_name' => '이새글',
            ],
            'terms' => [
                '(주)유닉코퍼레이션은 통신판매중개자로서 통신판매의 당사자가 아니며 상품, 상품정보, 거래에 관한 의무와 책임은 아티스트에게 있습니다.',
                '(주)유닉코퍼레이션 사이트의 상품/아티스트/중개 서비스/거래 정보, 콘텐츠, UI 등에 대한 무단 복제, 전송, 배포, 스크래핑 등의 행위는 저작권법, 콘텐츠산업 진흥법 등 관련법령에 의하여 엄격히 금지됩니다.'
            ],
            'settings' => $settings,
            'is_admin_page' => false,
        ]);
    }
}
