<?php

namespace Views;

use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Config\Services;
use Models\CodeProjectModel;
use Models\CustomFileModel;
use Models\SettingModel;
use Psr\Log\LoggerInterface;

class BaseClientController extends BaseViewController
{
    protected SettingModel $settingModel;
    protected CustomFileModel $customFileModel;
    protected CodeProjectModel $codeProjectModel;
    /**
     * to check login when user access page automatically
     * @var bool
     */
    protected bool $isCheckLogin = false;

    protected array $settings = [];

    public function __construct()
    {
        $this->settingModel = model('Models\SettingModel');
        $this->customFileModel = model('Models\CustomFileModel');
        $this->codeProjectModel = model('Models\CodeProjectModel');
        $settingResult = $this->settingModel->get();
        foreach ($settingResult as $item) {
            $this->settings[$item['code']] = $item['value'];
        }
    }

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        $this->setLanguage();
        if ($this->isCheckLogin) {
            $this->checkLogin();
        }
    }

    /**
     * login 상태일 때 페이지에 대한 접근 체크 기능
     * @return void
     */
    protected function checkLogin(): void
    {
        if ($this->session->is_login) {
            $response = Services::response();
            $response->setBody(view('/redirect', [
                'path' => '/profile',
            ]));
            $response->sendBody();
            exit;
        }
    }

    /**
     * logout 상태일 때 페이지에 대한 접근 체크 기능
     * @return void
     */
    protected function checkLogout(): void
    {
        if (!$this->session->is_login) {
            $response = Services::response();
            $response->setBody(view('/redirect', [
                'path' => '/',
            ]));
            $response->sendBody();
            exit;
        }
    }

    /**
     * 공통 header 부분 출력 기능
     * @param array $data
     * @param array $initData
     * @return string
     */
    protected function loadHeader(array $data, array $initData = []): string
    {
        $codeArtistResult = $this->codeProjectModel->get([]);
        $initData = array_merge(['is_main' => false], $initData);
        $initData = array_merge($initData, [
            'code_project' => $codeArtistResult,
            'settings' => $this->settings,
        ]);
        return view('/client/header', parent::loadDataForHeader($data, $initData));
    }

    /**
     * 공통 footer 부분 출력 기능
     * @return string
     */
    protected function loadFooter(): string
    {
        $initData = [
            'lang' => $this->session->lang,
        ];
        return view('/client/footer', $initData);
    }

    /**
     * body 출력 시에 공통적으로 load 될 데이터 호출 기능
     * @return array
     */
    protected function getViewData(): array
    {
        return array_merge(parent::getViewData(), [
            // todo translation
            'company_info' => [
                'name' => lang('Client.company_info_name'),
                'ceo_name' => lang('Client.company_info_ceo_name'),
                'cs_center' => lang('Client.company_info_cs_center'),
                'company_number' => lang('Client.company_info_company_number'),
                'certification_number' => lang('Client.company_info_certification_number'),
                'address' => lang('Client.company_info_address'),
                'email' => lang('Client.company_info_email'),
            ],
            'terms' => [
                lang('Client.terms_01'),
                lang('Client.terms_02'),
            ],
            'settings' => $this->settings,
            'is_admin_page' => false,
        ]);
    }
}
